language: node_js
nvm:
dist: focal
matrix:
  include:
  - node_js: "9"
    script: npm run test-with-temp-cloud
  - node_js: "10"
    script: npm run test-with-temp-cloud
  - node_js: "12"
    script: npm run test-with-temp-cloud
  - node_js: "14"
    script: npm run test-with-temp-cloud
  - node_js: "16"
    script: npm run test-with-temp-cloud
  - node_js: "18"
    script: npm run test-with-temp-cloud

notifications:
  email:
    recipients:
      - sdk_developers@cloudinary.com
