language: node_js
nvm:

matrix:
  include:
  - node_js: "6"
    before_install: npm install --global npm@6.14.18
    script: npm run test-with-temp-cloud
  - node_js: "8"
    script: npm run test-with-temp-cloud
  - node_js: "10"
    script: npm run test-with-temp-cloud
  - node_js: "12"
    script: npm run test-with-temp-cloud
  - node_js: "14"
    script: npm run test-with-temp-cloud
  - node_js: "16"
    script: npm run test-with-temp-cloud

notifications:
  email:
    recipients:
      - sdk_developers@cloudinary.com
